package com.example.studybuddy

const val MAX_MAJOR_SELECTIONS = 3

object BuMajors {
    val all: List<String> = listOf(
        "Accounting",
        "Advertising",
        "African American & Black Diaspora Studies",
        "American Studies",
        "Anthropology",
        "Archaeology",
        "Architectural Studies",
        "Art Education",
        "Art History",
        "Astronomy",
        "Biochemistry & Molecular Biology",
        "Biology",
        "Biomedical Engineering",
        "Biophysics",
        "Business Administration",
        "Chemistry",
        "Classical Civilization",
        "Communication Studies",
        "Computer Engineering",
        "Computer Science",
        "Dance",
        "Data Science",
        "Deaf Studies",
        "Earth & Environmental Sciences",
        "Economics",
        "Electrical Engineering",
        "Elementary Education",
        "English",
        "Environmental Analysis & Policy",
        "Environmental Engineering",
        "Environmental Science",
        "Film & Television",
        "Finance",
        "French Studies",
        "Graphic Design",
        "Health Science",
        "History",
        "Hospitality Administration",
        "Human Physiology",
        "International Relations",
        "Journalism",
        "Latin American Studies",
        "Linguistics",
        "Management Information Systems",
        "Marketing",
        "Materials Science & Engineering",
        "Mathematics",
        "Mechanical Engineering",
        "Media Science",
        "Music",
        "Music Education",
        "Neuroscience",
        "Nutrition Science",
        "Painting",
        "Philosophy",
        "Physics",
        "Political Science",
        "Printmaking",
        "Psychology",
        "Public Health",
        "Public Relations",
        "Religion",
        "Sculpture",
        "Sociology",
        "Spanish",
        "Speech, Language & Hearing Sciences",
        "Statistics",
        "Theatre Arts",
        "Urban Studies & Planning",
        "Visual Arts",
        "Women's, Gender & Sexuality Studies",
        "Youth Development & Education"
    ).sorted()
}
